.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH BLOCKFINDER 1 "MARCH 2014" Linux "User Manuals"
.SH NAME
blockfinder \- enumerates network information for countries
.SH SYNOPSIS
.B blockfinder -h
.SH DESCRIPTION
.B blockfinder
is currently undocumented. Please help improve this man page!

.SH AUTHOR
Jacob Appelbaum <jacob at appelbaum dot net>
